### ISSUE TITLE
ignore npm / yarn files

### ISSUE THREAD

**Issue by ticianomorvan** [Jothin-kumar/lines-of-code#2]
Files like `package.json`, `package-lock.json`, `yarn.lock`, etc. should be ignored because they aren't hand-written files.

**Comment by Jothin-kumar** [comment]
> Files like `package.json`, `package-lock.json`, `yarn.lock`, etc. should be ignored because they aren't hand-written files.

Tq for the suggestion! I am already working on this. This issue is similar to #1. Tq!

**Comment by ticianomorvan** [comment]
No problem! I really liked the tool, great work!

**Comment by Jothin-kumar** [comment]
> No problem! I really liked the tool, great work!

Tq for leaving a star :-)
