### ISSUE TITLE
Module Requirement

### ISSUE THREAD

**Issue by ShounenArgha** [Jothin-kumar/lines-of-code#4]
**Is your feature request related to a problem? Please describe.**
The problem is it needs a module called Github!
But i don't have it

**Describe the solution you'd like**
Please do a requirement.txt so that pip can read and install the neccesary modules so we don't have to face Module Problems.

**Describe alternatives you've considered**
I considered u can hardscript the program to install PYGithub or include in readme to install the requirements

**Additional context**
Don't need!

**Comment by ShounenArgha** [comment]
Thanks!!!
For adding it quickly

**Comment by Jothin-kumar** [comment]
@Arghadatta, `requirements.txt` is already present! it is now added to `README.md` :-)
